# Languages
# Documentation: https://docs.hugoblox.com/reference/language/

en:
  languageCode: en-us
  contentDir: content/en
  title: "c-ECO"
  weight: 1

pt:
  languageCode: pt-BR
  contentDir: content/pt
  title: "c-ECO"
  weight: 2
